---

version: '3.5'

networks:
  public:
    external: yes

volumes:
  html:
  html_old:

services:
  app:
    image: nas:5000/neuville
    volumes:
    - html:/srv/www:rw
#  www:
#    image: nas:5000/web-server
#    restart: always
#    volumes:
#    - html:/srv/web:ro
#    depends_on:
#    - app
#    labels:
#      traefik.enable: true
#      traefik.http.routers.neuville.rule: Host(`www.judo-neuville.eu.org`) || Host(`judo-neuville.eu.org`)
#      traefik.http.routers.neuville.middlewares: neuville-compress
#      traefik.http.middlewares.neuville-compress.compress: true
#    networks:
#    - public
  www:
    image: registry.ascalium.com/apache
    restart: always
    volumes:
    - html:/srv/www:ro
    tmpfs:
    - /run
    - /tmp
    - /var/tmp
    - /usr/local/apache2/logs
    depends_on:
    - app
    labels:
      traefik.enable: true
      traefik.http.routers.neuville.rule: Host(`www.judo-neuville.eu.org`) || Host(`judo-neuville.eu.org`)
      traefik.http.routers.neuville.middlewares: neuville-compress, neuville-headers
      traefik.http.middlewares.neuville-compress.compress: true
      traefik.http.middlewares.neuville-headers.headers.contentSecurityPolicy: frame-ancestors 'none'; script-src 'self'; img-src 'self' data:; frame-src 'none';
    networks:
    - public
  app_old:
    image: nas:5000/neuville:202102
    volumes:
    - html_old:/srv/www:rw
  www_old:
    image: registry.ascalium.com/apache
    restart: always
    volumes:
    - html_old:/srv/www:ro
    tmpfs:
    - /run
    - /tmp
    - /var/tmp
    - /usr/local/apache2/logs
    depends_on:
    - app
    labels:
      traefik.enable: true
      traefik.http.routers.neuville-old.rule: Host(`judo-neuville.s.alkahan.net`)
      traefik.http.routers.neuville-old.middlewares: neuville-old-compress
      traefik.http.middlewares.neuville-old-compress.compress: true
    networks:
    - public
